include: _template.yaml
task: openbookqa_gen
dataset_path: allenai/openbookqa
dataset_name: main
training_split: train
validation_split: validation
test_split: test
process_docs: !function utils.process_openbookqa
