include: _template.yaml
task: winogrande_gen
dataset_path: allenai/winogrande
dataset_name: winogrande_xl
training_split: train
validation_split: validation
process_docs: !function utils.process_winogrande
